create table if not exists companies (id uuid primary key default gen_random_uuid(), name text not null, category text not null check (category in ('Core','Dream','Super Dream')), reported_min_cgpa numeric(3,2) not null, reported_max_cgpa numeric(3,2), description text, created_at timestamptz default now());
create table if not exists placement_reports (id uuid primary key default gen_random_uuid(), company_id uuid references companies(id) on delete cascade, role text not null, graduation_year int not null, reported_cgpa numeric(3,2) not null, coding_difficulty text not null check (coding_difficulty in ('Easy','Medium','Hard')), interview_rounds text not null, questions text not null, reported_min_cgpa numeric(3,2), outcome text check (outcome in ('Selected','Rejected','Waitlisted','Not disclosed')), notes text, created_at timestamptz default now());
alter table companies enable row level security; alter table placement_reports enable row level security;
drop policy if exists "public read companies" on companies; create policy "public read companies" on companies for select using (true);
drop policy if exists "public read reports" on placement_reports; create policy "public read reports" on placement_reports for select using (true);
drop policy if exists "public insert reports" on placement_reports; create policy "public insert reports" on placement_reports for insert with check (true);
insert into companies (name,category,reported_min_cgpa,description) values ('TechNova','Dream',7.50,'DEMO DATA — fictional company used for the MVP.'),('DataSphere','Super Dream',8.20,'DEMO DATA — fictional company used for the MVP.'),('CloudCore','Dream',7.80,'DEMO DATA — fictional company used for the MVP.'),('FinEdge','Core',7.00,'DEMO DATA — fictional company used for the MVP.'),('CodeCraft','Super Dream',8.50,'DEMO DATA — fictional company used for the MVP.') on conflict do nothing;
-- Seed demo reports after companies are inserted. These are fictional/sample records and must not be presented as official SRM data.
insert into placement_reports(company_id,role,graduation_year,reported_cgpa,coding_difficulty,interview_rounds,questions,reported_min_cgpa,outcome,notes) select id,'Software Engineer',2027,8.10,'Medium','Technical + HR','Arrays, strings, OOP, project discussion',7.50,'Selected','DEMO/SAMPLE REPORT — fictional data.' from companies where name='TechNova' limit 1;
